development:
  adapter: postgresql
  database: my_database_development
  pool: 5
  host: localhost
  timeout: 5000
test:
  adapter: postgresql
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: admin_production
  username: admin
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
